### ISSUE TITLE
Jaws not deep linking in VitalSource Bookshelf Online in Chrome

### ISSUE THREAD

**Issue by GeorgeKerscher** [daisy/reading-system-testing#1]
### Issue Name: Jaws not deep linking in VitalSource Bookshelf Online in Chrome
 Steps:
 1. Launch Bookshelf online using Chrome and Jaws by going to the website:  https://bookshelf.vitalsource.com/#/
 2. Login using the  email for Freedom Tech support. VitalSource created the account and put a number of test titles in your library. Use the library functions and arrow down until you get to the title: fundamental basic accessibility tests 
 3. Open fundamental basic accessibility tests title
 4. Starting at the top, arrow down until you get to the table of contents button and activate.
 5. This opens the table of contents
6.  arrow down until you come to the section: "Navigation Tests" and press enter on this button. This will expand to show sub-sections. 

7. Move down until you get to:  navigate content by pages
 8. Press enter and observe visually that it takes you to the correct location, and it also reads out the correct text. . However, pressing the CTRL key to stop TTS or down arrow key to read the next line will jump you to the beginning of the chapter. This movement away from the correct location you navigated to causes the test to fail.
 
 Note:  We tested with the files extracted, and using only Chrome, this works properly.

OS: Windows 10  version 20H2
Reading System: VitalSource Bookshelf online
Version:
Chrome browser Version 86.0.4240.198 (Official Build) (64-bit)
Assistive Technology: Jaws 
AT version: Jaws version 2021.2012..57
AT case: Vispero Case# 00516961
Demonstration Video:  https://youtu.be/OnMyaFu1Kik

Sample file: Our fundamental basic accessibility test book

**Comment by marisademeglio** [comment]
The test book can be downloaded from http://epubtest.org/books/Fundamental-Accessibility-Tests-Basic-Functionality-v1.0.0.epub

**Comment by GeorgeKerscher** [comment]
Jaws is now deep linking in the Chrome browser.
