### ISSUE TITLE
Jaws does not recognize the HTML details element inside the HTML figure element in Chrome and in Thorium.

### ISSUE THREAD

**Issue by GeorgeKerscher** [daisy/reading-system-testing#2]
## Description
Using Jaws in Chrome or in Thorium Reader, move into a figure that contains a details element. When you get to the details, it is spoken, but there is no way to expand the details.

## Steps
1. Download the associated zip file, which contains both a HTML and an XHTML version that demonstrates the issue.
2.  Unzip the file and open the file in Chrome.
3. The file contains an simple explanation d of the issue, and a figure follows that contains a details element with a summary. This works fine in FireFox, but not in Chrome or Thorium. Thorium is based on Electron, so I suspect that when it is fixed in Chrome, it would also be fixed in Thorium, and George can confirm.
4.  Move down to the figure and read to where the details element is located.
Note that there is no way to activate the details element. If you use FireFox,  Jaws present a button to expand or collapse the details.

## OS
Windows 20 H2 and earlier

## Reading System
Thorium 1.5 and in Chrome

## Assistive Technology
Jaws 2020 and 2021
Jaws version 2021.2012.57

## Browser
Chrome 87
## Sample file

I am attaching a zip file with the XHTML  and a HTML  version inside the zip container. There are sub folders for images and styles used. 
No Freedom Scientific case number.
[Jaws-figure-details-issue-2.zip](https://github.com/daisy/reading-system-testing/files/5860615/Jaws-figure-details-issue-2.zip)

**Comment by jasonjgw** [comment]
If it hasn't been reported there already, I would suggest submitting the issue to the GitHub issue tracker at
https://github.com/FreedomScientific/VFO-standards-support

**Comment by GeorgeKerscher** [comment]
This problem has been resolved in Jaws 2022.
